language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem --version

rvm:
  - jruby
  - 2.0.0
  - 2.1.0

script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - surajshirvankar@gmail.com
    on_failure: change
    on_success: never